before_install:
    # ES5 needs this
    - sudo sysctl -w vm.max_map_count=262144
    # create log & bin dir if missing
    - mkdir -p $LOG_DIR
    - mkdir -p $BIN_DIR

    # install docker-compose if not in cache
    - if [ ! -f $COMPOSE_BIN ]; then curl -L {$COMPOSE_URI}/docker-compose-`uname -s`-`uname -m` -o $COMPOSE_BIN; fi
    - chmod +x $COMPOSE_BIN 

before_script:
    - $COMPOSE_BIN -f containers/dev/docker-compose.yml up -d > $COMPOSE_LOG
    # Wait ES
    - until curl http://127.0.0.1:9205/; do sleep 1; done

services:
    - docker 

env:
    global:
      - LOG_DIR=$HOME/log
      - BIN_DIR=$HOME/bin
      - COMPOSE_URI=https://github.com/docker/compose/releases/download/v2.17.2
      - COMPOSE_BIN=$HOME/bin/docker-compose-2-17-2
      - COMPOSE_LOG=$HOME/log/docker-compose.log
