version: '2'
services:
  elasticsearch-dev:
    image: elasticsearch:5.6.11
    environment:
      - xpack.security.enabled=false
      - cluster.name=elasticsearch
      - discovery.type=single-node
    ports:
      - "9205:9200"
      - "9305:9300"
